import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { homedir, platform } from 'node:os';
import { fileURLToPath } from 'node:url';
import {
  createConfig,
  resolveWizardConfigPath,
  ensureProjectGitignore,
  copySkill,
  installLaunchdPlist,
  schedulesGlobalConsolidation,
  parseRemote,
  type Scope,
  type RemoteSpec,
  resolveScope,
} from './init.js';
import { CYAN, GREEN, RESET, success, info, dim, warn } from './cli-output.js';
import { parseInitFlags, resolveInputMode, formatInitReport, type InitFlags } from './init-flags.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Resolves the destination file path for the OpenCode in-process plugin loader.
 */
export function getOpenCodePluginPath(scope: Scope): string {
  if (scope === 'project') {
    return join(process.cwd(), '.opencode', 'plugins', 'mcp-memory-graph.js');
  }
  return join(homedir(), '.config', 'opencode', 'plugins', 'mcp-memory-graph.js');
}

/**
 * Builds the loader JS module that dynamically imports dist/opencode/index.js.
 */
export function buildOpenCodePluginLoader(
  distOpencodePath: string,
  projectConfigPath?: string,
): string {
  const normalizedPath = distOpencodePath.replace(/\\/g, '/');
  if (projectConfigPath) {
    const normalizedConfig = projectConfigPath.replace(/\\/g, '/');
    return `// Auto-generated by mcp-memory-graph init
if (!process.env.MCP_MEMORY_CONFIG_PATH) {
  process.env.MCP_MEMORY_CONFIG_PATH = "${normalizedConfig}";
}
import plugin from "${normalizedPath}";
export default plugin;
`;
  }
  return `// Auto-generated by mcp-memory-graph init
import plugin from "${normalizedPath}";
export default plugin;
`;
}

/**
 * Removes any redundant mcp-memory-graph plugin entries from raw JSON/JSONC text,
 * preventing duplicate plugin instantiation since OpenCode auto-discovers plugins/.
 */
export function cleanOpenCodePluginConfig(raw: string): string {
  let parsed: any = {};
  try {
    parsed = parseJsonc(raw);
  } catch {
    return raw;
  }

  const isMemoryPlugin = (p: any): boolean =>
    (typeof p === 'string' && p.includes('mcp-memory-graph.js')) ||
    (Array.isArray(p) && typeof p[0] === 'string' && p[0].includes('mcp-memory-graph.js'));

  if (!Array.isArray(parsed?.plugin) || !parsed.plugin.some(isMemoryPlugin)) {
    return raw;
  }

  // Case 1: single entry in plugin array -> remove plugin block entirely
  if (parsed.plugin.length === 1) {
    const singleBlockRegex = /[ \t]*"plugin"\s*:\s*\[\s*"[^"\r\n]*mcp-memory-graph\.js"[^\]]*\],?[ \t]*\r?\n?/g;
    let stripped = raw.replace(singleBlockRegex, '');
    stripped = stripped.replace(/,(\s*[}\]])/g, '$1');
    try {
      JSON.parse(stripped);
      return stripped;
    } catch {
      try {
        parseJsonc(stripped);
        return stripped;
      } catch {
        // fallback below
      }
    }
  }

  // Case 2: multiple entries -> remove only the line with mcp-memory-graph.js
  const lineRegex = /[ \t]*"[^"\r\n]*mcp-memory-graph\.js"[ \t]*,?[ \t]*\r?\n?/g;
  let updated = raw.replace(lineRegex, '');
  updated = updated.replace(/,(\s*[}\]])/g, '$1');
  try {
    JSON.parse(updated);
    return updated;
  } catch {
    try {
      parseJsonc(updated);
      return updated;
    } catch {
      // Fallback to structured removal
      parsed.plugin = parsed.plugin.filter((p: any) => !isMemoryPlugin(p));
      if (parsed.plugin.length === 0) {
        delete parsed.plugin;
      }
      return JSON.stringify(parsed, null, 2) + '\n';
    }
  }
}

/**
 * Removes redundant mcp-memory-graph plugin entries from OpenCode config file.
 */
export function removeOpenCodePluginFromConfig(scope: Scope): void {
  const { path: configPath, exists } = findOpenCodeConfigPath(scope);
  if (!exists) return;
  try {
    const raw = readFileSync(configPath, 'utf-8');
    const updated = cleanOpenCodePluginConfig(raw);
    if (updated !== raw) {
      writeFileSync(configPath, updated, 'utf-8');
      info(`Removed redundant plugin entry from ${configPath}`);
    }
  } catch {
    // Non-blocking cleanup
  }
}

/**
 * Applies the plugin entry to raw JSON/JSONC text, ensuring OpenCode loads it.
 */
export function applyOpenCodePluginConfig(raw: string, pluginEntry: string): string {
  let parsed: any = {};
  try {
    parsed = parseJsonc(raw);
  } catch {
    parsed = {};
  }

  if (
    Array.isArray(parsed?.plugin) &&
    parsed.plugin.some(
      (p: any) =>
        (typeof p === 'string' && p === pluginEntry) ||
        (Array.isArray(p) && p[0] === pluginEntry),
    )
  ) {
    return raw;
  }

  const pluginMatch = raw.match(/"plugin"\s*:\s*\[/);
  if (pluginMatch && pluginMatch.index !== undefined) {
    const insertIdx = pluginMatch.index + pluginMatch[0].length;
    const rest = raw.slice(insertIdx);
    const firstNonWhitespace = rest.search(/\S/);
    const hasExistingProps = firstNonWhitespace !== -1 && rest[firstNonWhitespace] !== ']';
    const snippet = `\n    "${pluginEntry}"${hasExistingProps ? ',' : ''}`;
    const result = raw.slice(0, insertIdx) + snippet + raw.slice(insertIdx);
    try {
      parseJsonc(result);
      return result;
    } catch {
      /* fallback below */
    }
  }

  const rootMatch = raw.match(/\{/);
  if (rootMatch && rootMatch.index !== undefined) {
    const insertIdx = rootMatch.index + rootMatch[0].length;
    const rest = raw.slice(insertIdx);
    const firstNonWhitespace = rest.search(/\S/);
    const hasExistingProps = firstNonWhitespace !== -1 && rest[firstNonWhitespace] !== '}';
    const snippet = `\n  "plugin": [\n    "${pluginEntry}"\n  ]${hasExistingProps ? ',' : ''}`;
    const result = raw.slice(0, insertIdx) + snippet + raw.slice(insertIdx);
    try {
      parseJsonc(result);
      return result;
    } catch {
      /* fallback below */
    }
  }

  parsed.plugin = parsed.plugin || [];
  parsed.plugin.push(pluginEntry);
  return JSON.stringify(parsed, null, 2) + '\n';
}

/**
 * Registers the plugin entry into OpenCode configuration (opencode.jsonc / opencode.json).
 */
export function registerOpenCodePluginInConfig(scope: Scope): void {
  const { path: configPath, exists } = findOpenCodeConfigPath(scope);
  const pluginEntry =
    scope === 'project'
      ? './.opencode/plugins/mcp-memory-graph.js'
      : `file://${join(homedir(), '.config', 'opencode', 'plugins', 'mcp-memory-graph.js')}`;

  if (exists) {
    const raw = readFileSync(configPath, 'utf-8');
    try {
      const parsed = parseJsonc(raw);
      if (
        Array.isArray(parsed?.plugin) &&
        parsed.plugin.some(
          (p: any) =>
            (typeof p === 'string' && p === pluginEntry) ||
            (Array.isArray(p) && p[0] === pluginEntry),
        )
      ) {
        return;
      }
    } catch {
      /* fallback to string injection */
    }

    const updated = applyOpenCodePluginConfig(raw, pluginEntry);
    writeFileSync(configPath, updated, 'utf-8');
    success(`Registered plugin in ${configPath}`);
  } else {
    const configDir = dirname(configPath);
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }
    const initialConfig = {
      plugin: [pluginEntry],
    };
    writeFileSync(configPath, JSON.stringify(initialConfig, null, 2) + '\n', 'utf-8');
    success(`Created ${configPath} with plugin entry`);
  }
}

/**
 * Installs the OpenCode plugin loader module into ~/.config/opencode/plugins/
 * or .opencode/plugins/ (for project scope).
 */
export function installOpenCodePlugin(
  scope: Scope,
  distOpencodePath: string,
  projectConfigPath?: string,
): string {
  const pluginPath = getOpenCodePluginPath(scope);
  const pluginDir = dirname(pluginPath);
  if (!existsSync(pluginDir)) {
    mkdirSync(pluginDir, { recursive: true });
  }
  const content = buildOpenCodePluginLoader(distOpencodePath, projectConfigPath);
  writeFileSync(pluginPath, content, 'utf-8');
  success(`Installed OpenCode plugin loader at ${pluginPath}`);
  dim(`Loads plugin from ${distOpencodePath}`);
  removeOpenCodePluginFromConfig(scope);
  return pluginPath;
}

/**
 * Resolves the destination directory for the OpenCode usage skill.
 */
export function getOpenCodeSkillDir(scope: Scope): string {
  if (scope === 'project') {
    return join(process.cwd(), '.opencode', 'skills', 'mcp-memory-graph');
  }
  return join(homedir(), '.config', 'opencode', 'skills', 'mcp-memory-graph');
}

/**
 * Installs the mcp-memory-graph skill files into the OpenCode skills directory.
 */
export function installOpenCodeSkill(scope: Scope, enabled: boolean, skillSourceDir: string): void {
  if (!enabled) {
    dim('Skipping usage-skill install (--no-skill)');
    return;
  }
  const base = getOpenCodeSkillDir(scope);
  copySkill(skillSourceDir, base);
  if (existsSync(join(base, 'SKILL.md'))) {
    success(`Installed usage skill at ${base}`);
  }
}

/**
 * Locates the OpenCode config file (opencode.jsonc or opencode.json).
 */
export function findOpenCodeConfigPath(scope: Scope): { path: string; exists: boolean } {
  if (scope === 'project') {
    const candidates = [
      join(process.cwd(), 'opencode.jsonc'),
      join(process.cwd(), 'opencode.json'),
      join(process.cwd(), '.opencode', 'opencode.jsonc'),
      join(process.cwd(), '.opencode', 'opencode.json'),
    ];
    for (const p of candidates) {
      if (existsSync(p)) return { path: p, exists: true };
    }
    return { path: join(process.cwd(), 'opencode.jsonc'), exists: false };
  }

  const candidates = [
    join(homedir(), '.config', 'opencode', 'opencode.jsonc'),
    join(homedir(), '.config', 'opencode', 'opencode.json'),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return { path: p, exists: true };
  }
  return { path: join(homedir(), '.config', 'opencode', 'opencode.jsonc'), exists: false };
}

/**
 * Robust JSONC parser that strips comments (single-line and multi-line)
 * and trailing commas before JSON.parse.
 */
export function parseJsonc(content: string): any {
  let insideString = false;
  let stringChar = '';
  let isEscaped = false;
  let result = '';

  for (let i = 0; i < content.length; i++) {
    const char = content[i];
    const nextChar = content[i + 1];

    if (insideString) {
      result += char;
      if (char === '\\' && !isEscaped) {
        isEscaped = true;
      } else {
        if (char === stringChar && !isEscaped) {
          insideString = false;
        }
        isEscaped = false;
      }
    } else {
      if (char === '"' || char === "'") {
        insideString = true;
        stringChar = char;
        result += char;
      } else if (char === '/' && nextChar === '/') {
        while (i < content.length && content[i] !== '\n' && content[i] !== '\r') {
          i++;
        }
        if (i < content.length) result += content[i];
      } else if (char === '/' && nextChar === '*') {
        i += 2;
        while (i < content.length && !(content[i] === '*' && content[i + 1] === '/')) {
          i++;
        }
        i++;
      } else {
        result += char;
      }
    }
  }

  const cleaned = result.replace(/,(\s*[}\]])/g, '$1');
  return JSON.parse(cleaned);
}

/**
 * Builds the MCP memory server configuration block for OpenCode.
 */
export function buildOpenCodeMemoryConfig(opts: {
  distIndexPath: string;
  projectConfigPath?: string;
  env?: NodeJS.ProcessEnv;
  remote?: RemoteSpec | null;
}): Record<string, unknown> {
  if (opts.remote) {
    const trimmed = opts.remote.url.replace(/\/+$/, '');
    const url = /\/mcp$/.test(trimmed) ? trimmed : `${trimmed}/mcp`;
    const entry: Record<string, unknown> = {
      type: 'remote',
      url,
      enabled: true,
    };
    if (!opts.remote.noAuth) {
      const bearer = opts.remote.token
        ? opts.remote.token
        : `{env:${opts.remote.tokenEnv ?? 'MEMORY_MCP_TOKEN'}}`;
      entry.headers = { Authorization: `Bearer ${bearer}` };
    }
    return entry;
  }

  const env = opts.env ?? process.env;
  const isOllama = env.MCP_MEMORY_PROVIDER === 'ollama';

  if (isOllama) {
    const envVars: Record<string, string> = {
      MCP_CLIENT: 'opencode',
      MCP_STRIP_TOOL_PREFIX: '1',
      MCP_MEMORY_PROVIDER: 'ollama',
      MCP_MEMORY_MODEL: env.MCP_MEMORY_MODEL || 'nomic-embed-text',
      MCP_MEMORY_DIMENSIONS: env.MCP_MEMORY_DIMENSIONS || '768',
      OLLAMA_BASE_URL: env.OLLAMA_BASE_URL || 'http://localhost:11434',
      MCP_NLI_DISABLED: env.MCP_NLI_DISABLED || '1',
    };
    if (opts.projectConfigPath) {
      envVars.MCP_MEMORY_CONFIG_PATH = opts.projectConfigPath;
    }
    return {
      type: 'local',
      command: ['node', opts.distIndexPath],
      environment: envVars,
      timeout: 180000,
      enabled: true,
    };
  }

  const defaultEnv: Record<string, string> = {
    MCP_CLIENT: 'opencode',
    MCP_STRIP_TOOL_PREFIX: '1',
  };
  if (opts.projectConfigPath) {
    defaultEnv.MCP_MEMORY_CONFIG_PATH = opts.projectConfigPath;
  }
  const entry: Record<string, unknown> = {
    type: 'local',
    command: ['node', opts.distIndexPath],
    environment: defaultEnv,
    enabled: true,
  };
  return entry;
}

/**
 * Applies the memory MCP configuration to raw JSON/JSONC text,
 * preserving existing comments and structure where possible.
 */
export function applyOpenCodeMcpConfig(
  raw: string,
  memoryEntry: Record<string, unknown>,
): string {
  let parsed: any = {};
  try {
    parsed = parseJsonc(raw);
  } catch {
    parsed = {};
  }

  if (parsed?.mcp?.memory) {
    return raw;
  }

  const entryStr = JSON.stringify(memoryEntry, null, 2);
  const indentedEntry = entryStr
    .split('\n')
    .map((line, idx) => (idx === 0 ? line : '      ' + line))
    .join('\n');

  const mcpMatch = raw.match(/"mcp"\s*:\s*\{/);
  if (mcpMatch && mcpMatch.index !== undefined) {
    const insertIdx = mcpMatch.index + mcpMatch[0].length;
    const rest = raw.slice(insertIdx);
    const firstNonWhitespace = rest.search(/\S/);
    const hasExistingProps = firstNonWhitespace !== -1 && rest[firstNonWhitespace] !== '}';
    const snippet = `\n    "memory": ${indentedEntry}${hasExistingProps ? ',' : ''}`;
    const result = raw.slice(0, insertIdx) + snippet + raw.slice(insertIdx);
    try {
      parseJsonc(result);
      return result;
    } catch {
      /* fallback below */
    }
  }

  const rootMatch = raw.match(/\{/);
  if (rootMatch && rootMatch.index !== undefined) {
    const insertIdx = rootMatch.index + rootMatch[0].length;
    const rest = raw.slice(insertIdx);
    const firstNonWhitespace = rest.search(/\S/);
    const hasExistingProps = firstNonWhitespace !== -1 && rest[firstNonWhitespace] !== '}';
    const snippet = `\n  "mcp": {\n    "memory": ${indentedEntry}\n  }${hasExistingProps ? ',' : ''}`;
    const result = raw.slice(0, insertIdx) + snippet + raw.slice(insertIdx);
    try {
      parseJsonc(result);
      return result;
    } catch {
      /* fallback below */
    }
  }

  parsed.mcp = parsed.mcp || {};
  parsed.mcp.memory = memoryEntry;
  return JSON.stringify(parsed, null, 2) + '\n';
}

/**
 * Registers the memory MCP server in the OpenCode configuration file (opencode.jsonc / opencode.json).
 */
export function registerOpenCodeMcp(
  scope: Scope,
  enabled: boolean,
  distIndexPath: string,
  projectConfigPath?: string,
  remote?: RemoteSpec | null,
): void {
  if (!enabled) {
    dim('Skipping OpenCode MCP registration (--no-register)');
    return;
  }

  const { path: configPath, exists } = findOpenCodeConfigPath(scope);
  const memoryConfig = buildOpenCodeMemoryConfig({
    distIndexPath,
    projectConfigPath,
    remote,
  });

  if (exists) {
    const raw = readFileSync(configPath, 'utf-8');
    try {
      const parsed = parseJsonc(raw);
      if (parsed?.mcp?.memory) {
        info(`MCP server "memory" already registered in ${configPath} — leaving it untouched`);
        return;
      }
    } catch (e) {
      warn(`Could not parse ${configPath} as JSONC: ${e instanceof Error ? e.message : String(e)}`);
    }

    const updated = applyOpenCodeMcpConfig(raw, memoryConfig);
    writeFileSync(configPath, updated, 'utf-8');
    success(`Registered MCP server "memory" in ${configPath}`);
  } else {
    const configDir = dirname(configPath);
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }
    const initialConfig = {
      mcp: {
        memory: memoryConfig,
      },
    };
    writeFileSync(configPath, JSON.stringify(initialConfig, null, 2) + '\n', 'utf-8');
    success(`Created ${configPath} with MCP server "memory"`);
  }
}

/**
 * Builds the systemd service unit file content for consolidation.
 */
export function buildSystemdService(opts: {
  nodePath: string;
  distIndexPath: string;
}): string {
  return `[Unit]
Description=MCP Memory Graph nightly consolidation
Documentation=https://github.com/YonasValentin/mcp-memory-graph

[Service]
Type=oneshot
ExecStart=${opts.nodePath} ${opts.distIndexPath} consolidate
StandardOutput=journal
StandardError=journal
`;
}

/**
 * Builds the systemd timer unit file content for scheduled consolidation.
 */
export function buildSystemdTimer(
  schedule: Array<{ hour: number; minute: number }>,
): string {
  const onCalendarLines = schedule
    .map(
      ({ hour, minute }) =>
        `OnCalendar=*-*-* ${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00`,
    )
    .join('\n');

  return `[Unit]
Description=Run MCP Memory Graph consolidation daily
Documentation=https://github.com/YonasValentin/mcp-memory-graph

[Timer]
${onCalendarLines}
Persistent=true

[Install]
WantedBy=timers.target
`;
}

/**
 * Registers the TUI status widget plugin into OpenCode tui.json.
 */
export function registerOpenCodeTuiPlugin(scope: Scope, distTuiPath: string): void {
  const tuiPath =
    scope === 'project'
      ? join(process.cwd(), 'tui.json')
      : join(homedir(), '.config', 'opencode', 'tui.json');

  if (existsSync(tuiPath)) {
    try {
      const raw = readFileSync(tuiPath, 'utf-8');
      const parsed = parseJsonc(raw);
      if (Array.isArray(parsed?.plugin)) {
        if (parsed.plugin.includes(distTuiPath)) return;
        parsed.plugin.push(distTuiPath);
        writeFileSync(tuiPath, JSON.stringify(parsed, null, 2) + '\n', 'utf-8');
        success(`Registered TUI status plugin in ${tuiPath}`);
        return;
      }
    } catch {
      /* fallback */
    }
  } else {
    const dir = dirname(tuiPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    const content = {
      $schema: 'https://opencode.ai/tui.json',
      plugin: [distTuiPath],
    };
    writeFileSync(tuiPath, JSON.stringify(content, null, 2) + '\n', 'utf-8');
    success(`Created ${tuiPath} with TUI status plugin`);
  }
}

/**
 * Installs systemd user service + timer on Linux, or falls back to launchd/cron.
 */
export function installSystemdConsolidation(
  scope: Scope,
  schedule: Array<{ hour: number; minute: number }>,
  distIndexPath: string,
): void {
  if (!schedulesGlobalConsolidation(scope)) {
    info('Project scope — skipping the machine-global consolidation schedule');
    dim('A global systemd timer would target the default DB, not this project.');
    dim('Run `mcp-memory-graph init` (user scope) to schedule the default DB, or add a project cron manually:');
    dim(`  0 3 * * * MCP_MEMORY_DB_PATH=<project-db> ${process.execPath} ${distIndexPath} consolidate`);
    return;
  }

  if (platform() !== 'linux') {
    if (platform() === 'darwin') {
      installLaunchdPlist(scope);
      return;
    }
    info('Not on Linux — skipping systemd service installation');
    dim('To schedule nightly consolidation, add a cron entry:');
    dim(`  0 3 * * * ${process.execPath} ${distIndexPath} consolidate`);
    return;
  }

  const systemdUserDir = join(homedir(), '.config', 'systemd', 'user');
  const servicePath = join(systemdUserDir, 'mcp-memory-consolidate.service');
  const timerPath = join(systemdUserDir, 'mcp-memory-consolidate.timer');

  if (!existsSync(systemdUserDir)) {
    mkdirSync(systemdUserDir, { recursive: true });
  }

  const serviceContent = buildSystemdService({
    nodePath: process.execPath,
    distIndexPath,
  });
  const timerContent = buildSystemdTimer(schedule);

  writeFileSync(servicePath, serviceContent, 'utf-8');
  writeFileSync(timerPath, timerContent, 'utf-8');
  success(`Created systemd user service at ${servicePath}`);
  success(`Created systemd user timer at ${timerPath}`);

  const times = schedule
    .map(({ hour, minute }) => `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`)
    .join(', ');

  try {
    execFileSync('systemctl', ['--user', 'daemon-reload'], { stdio: 'ignore' });
    execFileSync('systemctl', ['--user', 'enable', '--now', 'mcp-memory-consolidate.timer'], { stdio: 'ignore' });
    success(`Enabled and started systemd user timer (daily at ${times})`);
  } catch {
    warn('Could not enable systemd user timer (systemctl --user failed)');
    info('To schedule nightly consolidation, add a cron entry instead:');
    dim(`  0 3 * * * ${process.execPath} ${distIndexPath} consolidate`);
  }
}

export interface OpenCodeInitOptions {
  scope?: Scope;
  projectScoped?: boolean;
  interactive?: boolean;
  flags?: InitFlags;
}

/**
 * Runs the OpenCode setup wizard and installation flow.
 */
export async function runOpenCodeInit(opts?: OpenCodeInitOptions): Promise<void> {
  const remote = parseRemote();

  const scope = opts?.scope ?? resolveScope();
  const projectScoped = opts?.projectScoped ?? (scope === 'project');
  const flags = opts?.flags ?? parseInitFlags(process.argv);
  const mode = resolveInputMode(process.argv, !!process.stdin.isTTY);
  const usePrompter = opts?.interactive ?? (mode !== 'defaults');

  const distOpencodePath = resolve(__dirname, '..', 'opencode', 'index.js');
  const distTuiPath = resolve(__dirname, '..', 'opencode', 'tui.js');
  const distIndexPath = resolve(__dirname, '..', 'index.js');
  const skillSourceDir = join(__dirname, '..', 'skill');

  console.log(`\n${CYAN}MCP Memory Graph — Init (OpenCode, ${scope} scope)${RESET}\n`);

  const { configPath: projectConfigPath } = resolveWizardConfigPath(projectScoped);

  info('Step 1/5: Installing OpenCode plugin...');
  installOpenCodePlugin(scope, distOpencodePath, projectScoped ? projectConfigPath : undefined);
  registerOpenCodeTuiPlugin(scope, distTuiPath);

  console.log('');
  info('Step 2/5: Installing usage skill...');
  installOpenCodeSkill(scope, flags.installSkill, skillSourceDir);

  console.log('');
  info('Step 3/5: Registering MCP server in OpenCode configuration...');
  registerOpenCodeMcp(
    scope,
    flags.registerServer,
    distIndexPath,
    projectScoped ? projectConfigPath : undefined,
    remote,
  );

  console.log('');
  info(`Step 4/5: Configuring memory (${mode === 'interactive' ? 'interactive wizard' : mode === 'defaults' ? 'defaults' : 'non-interactive'})...`);
  const config = await createConfig({ projectScoped, interactive: usePrompter, flags });
  if (scope === 'project') {
    ensureProjectGitignore();
  }

  if (mode === 'nonInteractive') {
    console.log('');
    info(formatInitReport(config, scope));
  }

  console.log('');
  info('Step 5/5: Installing scheduled consolidation...');
  let schedule: Array<{ hour: number; minute: number }>;
  try {
    schedule = flags.schedule ?? config.consolidation?.schedule ?? [{ hour: 3, minute: 0 }];
  } catch {
    schedule = flags.schedule ?? [{ hour: 3, minute: 0 }];
  }
  installSystemdConsolidation(scope, schedule, distIndexPath);

  console.log(`\n${GREEN}OpenCode init complete! (${scope} scope)${RESET}\n`);
}
