import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  getOpenCodePluginPath,
  buildOpenCodePluginLoader,
  installOpenCodePlugin,
  getOpenCodeSkillDir,
  installOpenCodeSkill,
  findOpenCodeConfigPath,
  parseJsonc,
  buildOpenCodeMemoryConfig,
  applyOpenCodeMcpConfig,
  registerOpenCodeMcp,
  buildSystemdService,
  buildSystemdTimer,
  installSystemdConsolidation,
} from '../../cli/init-opencode.js';

describe('OpenCode plugin loader', () => {
  it('buildOpenCodePluginLoader generates correct dynamic import module', () => {
    const loader = buildOpenCodePluginLoader('/path/to/dist/opencode/index.js');
    expect(loader).toContain('// Auto-generated by mcp-memory-graph init');
    expect(loader).toContain('import plugin from "/path/to/dist/opencode/index.js";');
    expect(loader).toContain('export default plugin;');
  });

  it('normalizes Windows backslashes in path', () => {
    const loader = buildOpenCodePluginLoader('C:\\Users\\test\\dist\\opencode\\index.js');
    expect(loader).toContain('import plugin from "C:/Users/test/dist/opencode/index.js";');
  });
});

describe('parseJsonc', () => {
  it('parses standard JSON', () => {
    const obj = parseJsonc('{"a": 1, "b": "hello"}');
    expect(obj).toEqual({ a: 1, b: 'hello' });
  });

  it('strips single-line comments', () => {
    const raw = `{\n  // A comment\n  "key": "value" // end of line\n}`;
    expect(parseJsonc(raw)).toEqual({ key: 'value' });
  });

  it('strips multi-line comments', () => {
    const raw = `{\n  /* A block comment\n     line 2 */\n  "key": "value"\n}`;
    expect(parseJsonc(raw)).toEqual({ key: 'value' });
  });

  it('preserves comment-like tokens inside string literals', () => {
    const raw = `{\n  "url": "https://example.com/*test*/",\n  "comment": "// this is not a comment"\n}`;
    expect(parseJsonc(raw)).toEqual({
      url: 'https://example.com/*test*/',
      comment: '// this is not a comment',
    });
  });

  it('handles trailing commas', () => {
    const raw = `{\n  "arr": [1, 2, ],\n  "obj": { "x": 1, },\n}`;
    expect(parseJsonc(raw)).toEqual({
      arr: [1, 2],
      obj: { x: 1 },
    });
  });
});

describe('buildOpenCodeMemoryConfig', () => {
  it('builds standard local stdio MCP server config', () => {
    const config = buildOpenCodeMemoryConfig({
      distIndexPath: '/dist/index.js',
      env: {},
    });
    expect(config).toEqual({
      type: 'local',
      command: ['node', '/dist/index.js'],
      enabled: true,
    });
  });

  it('includes projectConfigPath when specified', () => {
    const config = buildOpenCodeMemoryConfig({
      distIndexPath: '/dist/index.js',
      projectConfigPath: '/proj/.mcp-memory/config.json',
      env: {},
    });
    expect(config).toEqual({
      type: 'local',
      command: ['node', '/dist/index.js'],
      environment: {
        MCP_MEMORY_CONFIG_PATH: '/proj/.mcp-memory/config.json',
      },
      enabled: true,
    });
  });

  it('preserves Ollama environment variables when MCP_MEMORY_PROVIDER === ollama', () => {
    const config = buildOpenCodeMemoryConfig({
      distIndexPath: '/dist/index.js',
      env: {
        MCP_MEMORY_PROVIDER: 'ollama',
        MCP_MEMORY_MODEL: 'custom-model',
        MCP_MEMORY_DIMENSIONS: '1024',
        OLLAMA_BASE_URL: 'http://127.0.0.1:11434',
        MCP_NLI_DISABLED: '0',
      } as NodeJS.ProcessEnv,
    });
    expect(config).toEqual({
      type: 'local',
      command: ['node', '/dist/index.js'],
      environment: {
        MCP_MEMORY_PROVIDER: 'ollama',
        MCP_MEMORY_MODEL: 'custom-model',
        MCP_MEMORY_DIMENSIONS: '1024',
        OLLAMA_BASE_URL: 'http://127.0.0.1:11434',
        MCP_NLI_DISABLED: '0',
      },
      timeout: 180000,
      enabled: true,
    });
  });

  it('builds remote HTTP config when remote is supplied', () => {
    const config = buildOpenCodeMemoryConfig({
      distIndexPath: '/dist/index.js',
      remote: {
        url: 'http://my-server:3100',
        token: 'secret123',
      },
    });
    expect(config).toEqual({
      type: 'remote',
      url: 'http://my-server:3100/mcp',
      headers: {
        Authorization: 'Bearer secret123',
      },
      enabled: true,
    });
  });
});

describe('applyOpenCodeMcpConfig', () => {
  const memoryConfig = {
    type: 'local',
    command: ['node', '/dist/index.js'],
    enabled: true,
  };

  it('leaves content unchanged if mcp.memory is already present', () => {
    const raw = `{\n  "mcp": {\n    "memory": {\n      "type": "local"\n    }\n  }\n}`;
    const result = applyOpenCodeMcpConfig(raw, memoryConfig);
    expect(result).toBe(raw);
  });

  it('inserts into existing mcp object preserving other properties and comments', () => {
    const raw = `{\n  // User comments\n  "mcp": {\n    "github": { "type": "local" }\n  }\n}`;
    const result = applyOpenCodeMcpConfig(raw, memoryConfig);
    expect(result).toContain('// User comments');
    const parsed = parseJsonc(result);
    expect(parsed.mcp.memory).toEqual(memoryConfig);
    expect(parsed.mcp.github).toEqual({ type: 'local' });
  });

  it('inserts mcp block when mcp object does not exist', () => {
    const raw = `{\n  // Model configuration\n  "model": "gpt-4"\n}`;
    const result = applyOpenCodeMcpConfig(raw, memoryConfig);
    expect(result).toContain('// Model configuration');
    const parsed = parseJsonc(result);
    expect(parsed.model).toBe('gpt-4');
    expect(parsed.mcp.memory).toEqual(memoryConfig);
  });
});

describe('buildSystemdService & buildSystemdTimer', () => {
  it('builds systemd service unit correctly', () => {
    const service = buildSystemdService({
      nodePath: '/usr/bin/node',
      distIndexPath: '/path/dist/index.js',
    });
    expect(service).toContain('Description=MCP Memory Graph nightly consolidation');
    expect(service).toContain('ExecStart=/usr/bin/node /path/dist/index.js consolidate');
    expect(service).toContain('Type=oneshot');
  });

  it('builds systemd timer unit with OnCalendar schedule', () => {
    const timer = buildSystemdTimer([
      { hour: 3, minute: 0 },
      { hour: 15, minute: 30 },
    ]);
    expect(timer).toContain('OnCalendar=*-*-* 03:00:00');
    expect(timer).toContain('OnCalendar=*-*-* 15:30:00');
    expect(timer).toContain('Persistent=true');
    expect(timer).toContain('WantedBy=timers.target');
  });
});

describe('filesystem integration (temporary directory)', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'opencode-init-test-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('installOpenCodePlugin writes loader to target file', () => {
    const origCwd = process.cwd();
    process.chdir(tempDir);
    try {
      const written = installOpenCodePlugin('project', '/my/dist/opencode/index.js');
      expect(existsSync(written)).toBe(true);
      const content = readFileSync(written, 'utf-8');
      expect(content).toContain('import plugin from "/my/dist/opencode/index.js";');
      expect(content).toContain('export default plugin;');
    } finally {
      process.chdir(origCwd);
    }
  });

  it('registerOpenCodeMcp creates new config when absent', () => {
    const origCwd = process.cwd();
    process.chdir(tempDir);
    try {
      registerOpenCodeMcp('project', true, '/dist/index.js');
      const configPath = join(tempDir, 'opencode.jsonc');
      expect(existsSync(configPath)).toBe(true);
      const content = JSON.parse(readFileSync(configPath, 'utf-8'));
      expect(content.mcp.memory).toBeDefined();
      expect(content.mcp.memory.command).toEqual(['node', '/dist/index.js']);
    } finally {
      process.chdir(origCwd);
    }
  });

  it('registerOpenCodeMcp skips when disabled', () => {
    const origCwd = process.cwd();
    process.chdir(tempDir);
    try {
      registerOpenCodeMcp('project', false, '/dist/index.js');
      const configPath = join(tempDir, 'opencode.jsonc');
      expect(existsSync(configPath)).toBe(false);
    } finally {
      process.chdir(origCwd);
    }
  });
});
